#ifndef __COLOR_H__
#define __COLOR_H__

#define COLOR_RESET     "\033[0m"
#define COLOR_BOLD      "\033[1m"
#define COLOR_DIM       "\033[2m"
#define COLOR_UNDERLINE "\033[4m"
#define COLOR_BLINK     "\033[5m"
#define COLOR_REVERSE   "\033[7m"
#define COLOR_HIDDEN    "\033[8m"

#define COLOR_FG_DEFAULT      "\033[39m"
#define COLOR_FG_GREEN        "\033[32m"
#define COLOR_FG_YELLOW       "\033[33m"
#define COLOR_FG_BLUE         "\033[34m"
#define COLOR_FG_MAGENTA      "\033[35m"
#define COLOR_FG_CYAN         "\033[36m"

#define COLOR_BG_DEFAULT      "\033[49m"
#define COLOR_BG_BLACK        "\033[40m"
#define COLOR_BG_RED          "\033[41m"
#define COLOR_BG_GREEN        "\033[42m"
#define COLOR_BG_YELLOW       "\033[43m"
#define COLOR_BG_BLUE         "\033[44m"
#define COLOR_BG_MAGENTA      "\033[45m"
#define COLOR_BG_CYAN         "\033[46m"
#define COLOR_BG_LIGHTGRAY    "\033[47m"
#define COLOR_BG_DARKGRAY     "\033[100m"
#define COLOR_BG_LIGHTRED     "\033[101m"
#define COLOR_BG_LIGHTGREEN   "\033[102m"
#define COLOR_BG_LIGHTYELLOW  "\033[103m"
#define COLOR_BG_LIGHTBLUE    "\033[104m"
#define COLOR_BG_LIGHTMAGENTA "\033[105m"
#define COLOR_BG_LIGHTCYAN    "\033[106m"

#define COLOR_REG COLOR_FG_DEFAULT
#define COLOR_DIR COLOR_BOLD COLOR_FG_BLUE
#define COLOR_BLK COLOR_BOLD COLOR_FG_YELLOW COLOR_BG_DARKGRAY
#define COLOR_CHR COLOR_BOLD COLOR_FG_YELLOW COLOR_BG_DARKGRAY
#define COLOR_FIFO COLOR_FG_YELLOW COLOR_BG_DARKGRAY
#define COLOR_LINK COLOR_BOLD COLOR_FG_CYAN
#define COLOR_SOCK COLOR_BOLD COLOR_FG_MAGENTA
#define COLOR_EXE COLOR_BOLD COLOR_FG_GREEN

const int BG_SPEC_SIZE = 14;
static char* BG_SPECS[] = {
    COLOR_BG_DEFAULT,
    COLOR_BG_BLACK,
    COLOR_BG_RED,
    COLOR_BG_GREEN,
    COLOR_BG_YELLOW,
    COLOR_BG_BLUE,
    COLOR_BG_MAGENTA,
    COLOR_BG_CYAN,
    COLOR_BG_DARKGRAY,
    COLOR_BG_LIGHTRED,
    COLOR_BG_LIGHTGREEN,
    COLOR_BG_LIGHTYELLOW,
    COLOR_BG_LIGHTBLUE,
    COLOR_BG_LIGHTMAGENTA,
    COLOR_BG_LIGHTCYAN,
};

const int COLOR_LIST_SIZE = 4;
static char* COLOR_LIST[] = {
    COLOR_BOLD,
    COLOR_DIM,
    COLOR_UNDERLINE,
    COLOR_BLINK,
    COLOR_REVERSE
};

#endif
